export enum FareType {
    BRT = 'BRT',
    ARL = 'ARL',
    BTS = 'BTS',
    BTS_SILOM_EXTENSION_15 = 'BTS_SILOM_EXTENSION_15',
    BTS_SUKHUMVIT_EXTENSION_15 = 'BTS_SUKHUMVIT_EXTENSION_15',
    BTS_SUKHUMVIT_EXTENSION_0 = 'BTS_SUKHUMVIT_EXTENSION_0',
    MRT_BLUE = 'MRT_BLUE',
    MRT_PURPLE = 'MRT_PURPLE',
}