name: Manual-build-test-deploy-s3

on: workflow_dispatch

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: run test coverage
        run: yarn test:coverage

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: metrofare-build
          path: ./build/

  deploy:
    name: Deploying to test env
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: metrofare-build
          path: ./build/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://test-deploy-web-from-github-action --delete
